# kinematics.yaml
# Note: This file defines parameters used by the following classes - AnalyticalSolver, PinocchioSolver

urdf_filepath: "urdf/3dof_arm.urdf"  # Must be relative to kinematics.yaml itself

AnalyticalSolver:
  link_length_source: "yaml"  # Pick urdf or yaml here

  # Link lengths (only used if yaml is selected above)
  link_lengths: [0.3, 0.3, 0.1]  # L1, L2, L3
  
  use_lookup_table_speedup: false
  
  # Joint limits in degrees [min, max] for each joint
  joint_limits:
    - [-178, 178]  # Joint 1
    - [-178, 178]  # Joint 2
    - [-178, 178]  # Joint 3

PinocchioSolver:
  use_lookup_table_speedup: false
  # Note: no joint limits here: PinocchioSolver parses joint limits from URDF