# kinematics.yaml
# Note: This file defines parameters used by the following classes - Kinematics, CustomSolver, PinocchioSolver

# kinematics.yaml
solver_type: "CustomSolver"  # CustomSolver or PinocchioSolver
urdf_filepath: "./include/planar_arm_kinematics/config/urdf/planar_arm.urdf"

CustomSolver:
  parse_lengths_from_urdf_vs_yaml: "yaml"  # Pick urdf or yaml here
  
  # Link lengths (only used if yaml is selected above)
  link_lengths: [0.3, 0.3, 0.1]  # L1, L2, L3
  
  use_lookup_table_speedup: false
  
  # Joint limits in degrees [min, max] for each joint
  joint_limits:
    - [-178, 178]  # Joint 1
    - [-178, 178]  # Joint 2
    - [-178, 178]  # Joint 3

PinocchioSolver:
  use_lookup_table_speedup: false